spring:
    datasource:
        generate-unique-name: false
        name: todayilearned
    profiles:
        active:
            - dev
    custom:
        algolia-application-id: 0UGOGVIXV6
        algolia-indexing-api-key: 66431061e984f622a44404c4d6caf169

---
spring:
    profiles: dev
    mail:
        debug: true
        host: smtp.gmail.com
        password: qkvodywtwkischrg
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        transport:
            protocol: smtp
        username: cuppajoe43@gmail.com

    custom:
        domain-name: "localhost:8080"
        algolia-index-name: dev_Submissions

---
spring:
    profiles: prod
    datasource:
        url: jdbc:postgresql://192.168.50.224:5432/todayilearned
        username: postgres
        password: password
    jpa:
        database: POSTGRESQL
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
    mail:
        debug: true
        test-connection: true
        host: smtp.porkbun.com
        username: noreply@today-i-learned.xyz
        password: "WcK4yT9zJAAg3is"
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        transport:
            protocol: smtp

    custom:
        domain-name: "today-i-learned.xyz"
        algolia-index-name: prod_Submissions
