spring:
    datasource:
        generate-unique-name: false
        name: todayilearned
    profiles:
        active:
            - prod

---
spring:
    profiles: dev
    mail:
        debug: true
        host: smtp.gmail.com
        password: qkvodywtwkischrg
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        transport:
            protocol: smtp
        username: cuppajoe43@gmail.com

---
spring:
    profiles: prod
    mail:
        debug: true
        test-connection: true
        host: smtp.porkbun.com
        username: noreply@today-i-learned.xyz
        password: "WcK4yT9zJAAg3is"
        port: 587
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        transport:
            protocol: smtp

