services:
  db:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    user: "1000:1000"
    environment:
      POSTGRES_PASSWORD: password
    network_mode: host
    volumes:
      - '/etc/passwd:/etc/passwd:ro'
      - '/home/joe/todayilearned/docker/pgdata:/var/lib/postgresql/data'

  today-i-learned:
    container_name: today-i-learned
    image: library/today-i-learned:0.0.1-SNAPSHOT
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - db

#  letsencrypt-nginx-container:
#    container_name: 'letsencrypt-nginx-container'
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - /docker/letsencrypt-docker-nginx/src/letsencrypt/letsencrypt-site:/usr/share/nginx/html/
#    networks:
#      - docker-network

  production-nginx-container:
    container_name: 'production-nginx-container'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./production.conf:/etc/nginx/conf.d/default.conf
      - ./production-site:/usr/share/nginx/html
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/today-i-learned.xyz/fullchain.pem:/etc/letsencrypt/live/today-i-learned.xyz/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/today-i-learned.xyz/privkey.pem:/etc/letsencrypt/live/today-i-learned.xyz/privkey.pem
#    networks:
#      - docker-network

#networks:
#  docker-network:
#    driver: bridge

volumes:
    pgdata:
