version: "3"

services:
    db:
        container_name: postgres
        image: postgres
        restart: unless-stopped
        user: "1000:1000"
        environment:
            POSTGRES_PASSWORD: password
        network_mode: host
        volumes:
            - '/etc/passwd:/etc/passwd:ro'
            - '/home/joe/today-i-learned/docker/pgdata:/var/lib/postgresql/data'

    today-i-learned:
        container_name: today-i-learned
        image: library/today-i-learned:0.0.1-SNAPSHOT
        ports:
            - '8082:8082'
        restart: unless-stopped
        depends_on:
            - db

volumes:
    pgdata:


